### PR TITLE
Fix AttributeError on sys.stderr.fileno

### PR DESCRIPTION
**Pull request by EikeDehling**
Using the latest version of exact online API in nginx environment causes errors:

```
Error exporting relations
Traceback (most recent call last):
  File "/var/app/current/app/tasks.py", line 162, in exactonline_export_relations_task
    export_one_relation(api, relations_by_code, relations_by_name, item['organisation'], location['location'])
  File "/var/app/current/app/tasks.py", line 138, in export_one_relation
    api.relations.update(existing_relation['ID'], relation_data)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/exactonline/api/manager.py", line 104, in update
    ret = self._api.restv1(PUT(str(uri), element_dict))
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/exactonline/api/v1division.py", line 30, in restv1
    return self.rest(request)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/exactonline/api/unwrap.py", line 25, in rest
    decoded = super(Unwrap, self).rest(request)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/exactonline/api/autorefresh.py", line 51, in rest
    decoded = super(Autorefresh, self).rest(request)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/exactonline/rawapi.py", line 229, in rest
    response = self._rest_query(new_request)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/exactonline/rawapi.py", line 250, in _rest_query
    self.limiter.backoff()
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/exactonline/rawapi.py", line 59, in backoff
    self.wait(seconds)
  File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/exactonline/rawapi.py", line 69, in wait
    if sys.stderr and os.isatty(sys.stderr.fileno()):
AttributeError: 'LoggingProxy' object has no attribute 'fileno'
```

### CODE REVIEW

**Comment by wdoekes** [comment]
I find this PR kind of insulting. 

The code doesn't work on your system, so let's just drop it without considering who _might_ use it? :thinking:

I would've considered removing the code, but not by calling it "fix attributeerror".

**Comment by EikeDehling** [comment]
Would you prefer checking for the fileno attribute?  Or would you have another solution in mind?

Not trying to insult anyone, just solving issues so the package works better for everyone...

**Comment by wdoekes** [comment]
Well, your commit message reads:

> Fix AttributeError on stderr.fileno when using the api from nginx

So the changeset fixes that no AttributeError is tripped _when using nginx._ The message implies that other use(r)s are unaffected.

> Would you prefer checking for the fileno attribute?

That would be the easiest solution. Apparently stderr does not have a fileno in your case. If it doesn't have a fileno() I'm fine with the assumption that it is not a tty either.

**Comment by EikeDehling** [comment]
Changes updated as suggested

**Comment by wdoekes** [comment]
Better. Except the line is (way) too long and the getattr() is superfluous.
```console
$ python3 -c 'x=4; print(hasattr(x, "fileno") and x.fileno())'
False
```

But I wonder what kind of python interface you're running. Nginx doesn't do python, so you'd need a plugin or a python (wsgi) backend.

I wonder, because using `isatty` would be even cleaner:
```console
$ python3 -c 'import sys; print(sys.stderr.isatty())'
True
```
But I cannot tell if `isatty` exists on that `LoggingProxy` you have there.

**Comment by EikeDehling** [comment]
Updated the pull request as suggested.

It appears the actual object for sys.stderr is this one, it's from celery and it supports the .isatty() call:

https://github.com/celery/celery/blob/9ff86cd5f0b32e0167c8481020c177bd72308ee5/celery/utils/log.py#L258

**Comment by wdoekes** [comment]
TY

**Pull request merged**
